# Generated by Django 4.2 on 2023-05-14 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_remove_room_updated_at_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="members",
            name="user",
        ),
        migrations.AddField(
            model_name="members",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
