# Generated by Django 4.2.1 on 2023-05-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_remove_members_user_members_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="user",
            field=models.ManyToManyField(to="chat.userprofile"),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.userprofile"
            ),
        ),
    ]
