# Generated by Django 4.2.1 on 2023-06-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_members_user_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
